version: 2

models:
  - name: stg_users
    description: "Cleaned and standardized users"
    columns:
      - name: user_id
        description: "Primary key for users"
        tests:
          - not_null
          - unique

  - name: stg_user_sources
    description: "User-level marketing channel mapping"
    columns:
      - name: user_id
        description: "Links each user to their acquisition channel"
        tests:
          - not_null