version: 2

models:
  - name: mart_users
    description: One row per user with core user attributes
    columns:
      - name: user_id
        description: Primary key for users
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_users')
              field: user_id

  - name: mart_users_with_source
    description: Users enriched with marketing acquisition source
    columns:
      - name: user_id
        description: Foreign key to mart_users
        tests:
          - not_null
          - relationships:
              to: ref('mart_users')
              field: user_id

  - name: mart_channel_performance
    description: Aggregated performance metrics by marketing channel
    columns:
      - name: source
        description: Marketing acquisition source / channel
        tests:
          - not_null
          
  - name: customer_ltv
    description: Customer lifetime value (historical)
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
