version: 2

sources:
  - name: raw
    description: >
      Raw, immutable data ingested from the application database and marketing platforms.
      These tables represent the source-of-truth for all downstream analytics models in this project.
      No transformations should be performed in this schema — only cleaning and modeling downstream.

    database: MARKETING_ANALYTICS
    schema: RAW

    tables:
      - name: users
        description: >
          One record per user who has created an account or been identified by the product.
          This table is the foundation for customer analytics, cohort analysis, and lifetime value calculations.
        columns:
          - name: user_id
            description: Unique identifier for each user.
          - name: created_at
            description: Timestamp when the user first registered or was first seen.
          - name: email
            description: Email address associated with the user account.
          - name: country
            description: Country of the user, if known.

      - name: user_sources
        description: >
          Attribution table linking each user to the marketing channel or campaign that acquired them.
          This table is used to calculate CAC, ROAS, and channel-level performance metrics.
        columns:
          - name: user_id
            description: Unique identifier of the user who was acquired.
          - name: source
            description: High-level marketing channel such as Google, Facebook, or Organic.
          - name: campaign
            description: Specific campaign or ad group responsible for acquisition.
          - name: acquired_at
            description: Timestamp when the user was attributed to this source.

      - name: orders
        description: >
          Transaction-level purchase data.
          Each row represents a single completed order placed by a user.
          This table is used to calculate revenue, conversion, and lifetime value.
        columns:
          - name: order_id
            description: Unique identifier for each order.
          - name: user_id
            description: User who placed the order.
          - name: order_date
            description: Date when the order was completed.
          - name: amount
            description: Revenue generated by the order, in the warehouse currency.

      - name: marketing_spend
        description: >
          Daily advertising spend by marketing channel and campaign.
          This table is used to calculate CAC and ROAS across acquisition sources.
        columns:
          - name: spend_date
            description: Date the marketing spend was incurred.
          - name: source
            description: Marketing channel where the spend occurred.
          - name: campaign
            description: Campaign or ad group the spend is associated with.
          - name: spend
            description: Amount of money spent on that day for the campaign.