version: 2

sources:
  - name: raw
    description: "Raw marketing and ecommerce data loaded from upstream systems"
    database: MARKETING_ANALYTICS
    schema: RAW

    tables:
      - name: users
        description: "Raw user records from the ecommerce platform"

      - name: user_sources
        description: "Raw marketing attribution data mapping users to acquisition channels"